name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  py-linter:
    name: Python Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: "true"

      - name: Install Python dependencies with UV
        run: uv sync

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  js-linter:
    name: JavaScript/TypeScript/Bun/HTML/CSS/Sass Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install JS dependencies with Bun
        run: bun install

      - name: Run ESLint and check Prettier formatting
        run: bun run check

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f docker-compose.local.yml build django

      - name: Build the docs
        run: docker compose -f docker-compose.docs.yml build docs

      - name: Check DB Migrations
        run: docker compose -f docker-compose.local.yml run --rm django uv run python manage.py makemigrations --check

      - name: Run DB Migrations
        run: docker compose -f docker-compose.local.yml run --rm django uv run python manage.py migrate

      - name: Run Django Tests
        run: docker compose -f docker-compose.local.yml run django pytest

      - name: Tear down the Stack
        run: docker compose -f docker-compose.local.yml down
